# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/heck/prog/cpp/vulkan/EnforcerScyphozia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/heck/prog/cpp/vulkan/EnforcerScyphozia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/heck/prog/cpp/vulkan/EnforcerScyphozia/CMakeFiles /home/heck/prog/cpp/vulkan/EnforcerScyphozia//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/heck/prog/cpp/vulkan/EnforcerScyphozia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EnforcerSyphozia

# Build rule for target.
EnforcerSyphozia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EnforcerSyphozia
.PHONY : EnforcerSyphozia

# fast build rule for target.
EnforcerSyphozia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/build
.PHONY : EnforcerSyphozia/fast

#=============================================================================
# Target rules for targets named custom_clean

# Build rule for target.
custom_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 custom_clean
.PHONY : custom_clean

# fast build rule for target.
custom_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/custom_clean.dir/build.make CMakeFiles/custom_clean.dir/build
.PHONY : custom_clean/fast

#=============================================================================
# Target rules for targets named rebuild

# Build rule for target.
rebuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebuild
.PHONY : rebuild

# fast build rule for target.
rebuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rebuild.dir/build.make CMakeFiles/rebuild.dir/build
.PHONY : rebuild/fast

common/assert.o: common/assert.cpp.o
.PHONY : common/assert.o

# target to build an object file
common/assert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/assert.cpp.o
.PHONY : common/assert.cpp.o

common/assert.i: common/assert.cpp.i
.PHONY : common/assert.i

# target to preprocess a source file
common/assert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/assert.cpp.i
.PHONY : common/assert.cpp.i

common/assert.s: common/assert.cpp.s
.PHONY : common/assert.s

# target to generate assembly for a file
common/assert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/assert.cpp.s
.PHONY : common/assert.cpp.s

common/config.o: common/config.cpp.o
.PHONY : common/config.o

# target to build an object file
common/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/config.cpp.o
.PHONY : common/config.cpp.o

common/config.i: common/config.cpp.i
.PHONY : common/config.i

# target to preprocess a source file
common/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/config.cpp.i
.PHONY : common/config.cpp.i

common/config.s: common/config.cpp.s
.PHONY : common/config.s

# target to generate assembly for a file
common/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/config.cpp.s
.PHONY : common/config.cpp.s

common/discord.o: common/discord.cpp.o
.PHONY : common/discord.o

# target to build an object file
common/discord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/discord.cpp.o
.PHONY : common/discord.cpp.o

common/discord.i: common/discord.cpp.i
.PHONY : common/discord.i

# target to preprocess a source file
common/discord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/discord.cpp.i
.PHONY : common/discord.cpp.i

common/discord.s: common/discord.cpp.s
.PHONY : common/discord.s

# target to generate assembly for a file
common/discord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/discord.cpp.s
.PHONY : common/discord.cpp.s

common/logging/filter.o: common/logging/filter.cpp.o
.PHONY : common/logging/filter.o

# target to build an object file
common/logging/filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/logging/filter.cpp.o
.PHONY : common/logging/filter.cpp.o

common/logging/filter.i: common/logging/filter.cpp.i
.PHONY : common/logging/filter.i

# target to preprocess a source file
common/logging/filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/logging/filter.cpp.i
.PHONY : common/logging/filter.cpp.i

common/logging/filter.s: common/logging/filter.cpp.s
.PHONY : common/logging/filter.s

# target to generate assembly for a file
common/logging/filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/logging/filter.cpp.s
.PHONY : common/logging/filter.cpp.s

common/logging/text_formatter.o: common/logging/text_formatter.cpp.o
.PHONY : common/logging/text_formatter.o

# target to build an object file
common/logging/text_formatter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/logging/text_formatter.cpp.o
.PHONY : common/logging/text_formatter.cpp.o

common/logging/text_formatter.i: common/logging/text_formatter.cpp.i
.PHONY : common/logging/text_formatter.i

# target to preprocess a source file
common/logging/text_formatter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/logging/text_formatter.cpp.i
.PHONY : common/logging/text_formatter.cpp.i

common/logging/text_formatter.s: common/logging/text_formatter.cpp.s
.PHONY : common/logging/text_formatter.s

# target to generate assembly for a file
common/logging/text_formatter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/common/logging/text_formatter.cpp.s
.PHONY : common/logging/text_formatter.cpp.s

external/imgui/backends/imgui_impl_glfw.o: external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.o

# target to build an object file
external/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.o

external/imgui/backends/imgui_impl_glfw.i: external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.i

external/imgui/backends/imgui_impl_glfw.s: external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.s

external/imgui/backends/imgui_impl_vulkan.o: external/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : external/imgui/backends/imgui_impl_vulkan.o

# target to build an object file
external/imgui/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : external/imgui/backends/imgui_impl_vulkan.cpp.o

external/imgui/backends/imgui_impl_vulkan.i: external/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : external/imgui/backends/imgui_impl_vulkan.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : external/imgui/backends/imgui_impl_vulkan.cpp.i

external/imgui/backends/imgui_impl_vulkan.s: external/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : external/imgui/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : external/imgui/backends/imgui_impl_vulkan.cpp.s

external/imgui/imgui.o: external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.o

# target to build an object file
external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.cpp.o

external/imgui/imgui.i: external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_demo.o: external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.o

# target to build an object file
external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.cpp.o

external/imgui/imgui_demo.i: external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.i

# target to preprocess a source file
external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.cpp.i

external/imgui/imgui_demo.s: external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.s

# target to generate assembly for a file
external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.cpp.s

external/imgui/imgui_draw.o: external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.o

# target to build an object file
external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.cpp.o

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_tables.o: external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.o

# target to build an object file
external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.cpp.o

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.o: external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.o

# target to build an object file
external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.cpp.o

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

game/player.o: game/player.cpp.o
.PHONY : game/player.o

# target to build an object file
game/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/game/player.cpp.o
.PHONY : game/player.cpp.o

game/player.i: game/player.cpp.i
.PHONY : game/player.i

# target to preprocess a source file
game/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/game/player.cpp.i
.PHONY : game/player.cpp.i

game/player.s: game/player.cpp.s
.PHONY : game/player.s

# target to generate assembly for a file
game/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/game/player.cpp.s
.PHONY : game/player.cpp.s

src/application.o: src/application.cpp.o
.PHONY : src/application.o

# target to build an object file
src/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/application.cpp.o
.PHONY : src/application.cpp.o

src/application.i: src/application.cpp.i
.PHONY : src/application.i

# target to preprocess a source file
src/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/application.cpp.i
.PHONY : src/application.cpp.i

src/application.s: src/application.cpp.s
.PHONY : src/application.s

# target to generate assembly for a file
src/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/application.cpp.s
.PHONY : src/application.cpp.s

src/enf_buffer.o: src/enf_buffer.cpp.o
.PHONY : src/enf_buffer.o

# target to build an object file
src/enf_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_buffer.cpp.o
.PHONY : src/enf_buffer.cpp.o

src/enf_buffer.i: src/enf_buffer.cpp.i
.PHONY : src/enf_buffer.i

# target to preprocess a source file
src/enf_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_buffer.cpp.i
.PHONY : src/enf_buffer.cpp.i

src/enf_buffer.s: src/enf_buffer.cpp.s
.PHONY : src/enf_buffer.s

# target to generate assembly for a file
src/enf_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_buffer.cpp.s
.PHONY : src/enf_buffer.cpp.s

src/enf_camera.o: src/enf_camera.cpp.o
.PHONY : src/enf_camera.o

# target to build an object file
src/enf_camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_camera.cpp.o
.PHONY : src/enf_camera.cpp.o

src/enf_camera.i: src/enf_camera.cpp.i
.PHONY : src/enf_camera.i

# target to preprocess a source file
src/enf_camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_camera.cpp.i
.PHONY : src/enf_camera.cpp.i

src/enf_camera.s: src/enf_camera.cpp.s
.PHONY : src/enf_camera.s

# target to generate assembly for a file
src/enf_camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_camera.cpp.s
.PHONY : src/enf_camera.cpp.s

src/enf_descriptors.o: src/enf_descriptors.cpp.o
.PHONY : src/enf_descriptors.o

# target to build an object file
src/enf_descriptors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_descriptors.cpp.o
.PHONY : src/enf_descriptors.cpp.o

src/enf_descriptors.i: src/enf_descriptors.cpp.i
.PHONY : src/enf_descriptors.i

# target to preprocess a source file
src/enf_descriptors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_descriptors.cpp.i
.PHONY : src/enf_descriptors.cpp.i

src/enf_descriptors.s: src/enf_descriptors.cpp.s
.PHONY : src/enf_descriptors.s

# target to generate assembly for a file
src/enf_descriptors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_descriptors.cpp.s
.PHONY : src/enf_descriptors.cpp.s

src/enf_device.o: src/enf_device.cpp.o
.PHONY : src/enf_device.o

# target to build an object file
src/enf_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_device.cpp.o
.PHONY : src/enf_device.cpp.o

src/enf_device.i: src/enf_device.cpp.i
.PHONY : src/enf_device.i

# target to preprocess a source file
src/enf_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_device.cpp.i
.PHONY : src/enf_device.cpp.i

src/enf_device.s: src/enf_device.cpp.s
.PHONY : src/enf_device.s

# target to generate assembly for a file
src/enf_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_device.cpp.s
.PHONY : src/enf_device.cpp.s

src/enf_game_object.o: src/enf_game_object.cpp.o
.PHONY : src/enf_game_object.o

# target to build an object file
src/enf_game_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_game_object.cpp.o
.PHONY : src/enf_game_object.cpp.o

src/enf_game_object.i: src/enf_game_object.cpp.i
.PHONY : src/enf_game_object.i

# target to preprocess a source file
src/enf_game_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_game_object.cpp.i
.PHONY : src/enf_game_object.cpp.i

src/enf_game_object.s: src/enf_game_object.cpp.s
.PHONY : src/enf_game_object.s

# target to generate assembly for a file
src/enf_game_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_game_object.cpp.s
.PHONY : src/enf_game_object.cpp.s

src/enf_interface.o: src/enf_interface.cpp.o
.PHONY : src/enf_interface.o

# target to build an object file
src/enf_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_interface.cpp.o
.PHONY : src/enf_interface.cpp.o

src/enf_interface.i: src/enf_interface.cpp.i
.PHONY : src/enf_interface.i

# target to preprocess a source file
src/enf_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_interface.cpp.i
.PHONY : src/enf_interface.cpp.i

src/enf_interface.s: src/enf_interface.cpp.s
.PHONY : src/enf_interface.s

# target to generate assembly for a file
src/enf_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_interface.cpp.s
.PHONY : src/enf_interface.cpp.s

src/enf_model.o: src/enf_model.cpp.o
.PHONY : src/enf_model.o

# target to build an object file
src/enf_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_model.cpp.o
.PHONY : src/enf_model.cpp.o

src/enf_model.i: src/enf_model.cpp.i
.PHONY : src/enf_model.i

# target to preprocess a source file
src/enf_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_model.cpp.i
.PHONY : src/enf_model.cpp.i

src/enf_model.s: src/enf_model.cpp.s
.PHONY : src/enf_model.s

# target to generate assembly for a file
src/enf_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_model.cpp.s
.PHONY : src/enf_model.cpp.s

src/enf_pipeline.o: src/enf_pipeline.cpp.o
.PHONY : src/enf_pipeline.o

# target to build an object file
src/enf_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_pipeline.cpp.o
.PHONY : src/enf_pipeline.cpp.o

src/enf_pipeline.i: src/enf_pipeline.cpp.i
.PHONY : src/enf_pipeline.i

# target to preprocess a source file
src/enf_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_pipeline.cpp.i
.PHONY : src/enf_pipeline.cpp.i

src/enf_pipeline.s: src/enf_pipeline.cpp.s
.PHONY : src/enf_pipeline.s

# target to generate assembly for a file
src/enf_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_pipeline.cpp.s
.PHONY : src/enf_pipeline.cpp.s

src/enf_raycast.o: src/enf_raycast.cpp.o
.PHONY : src/enf_raycast.o

# target to build an object file
src/enf_raycast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_raycast.cpp.o
.PHONY : src/enf_raycast.cpp.o

src/enf_raycast.i: src/enf_raycast.cpp.i
.PHONY : src/enf_raycast.i

# target to preprocess a source file
src/enf_raycast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_raycast.cpp.i
.PHONY : src/enf_raycast.cpp.i

src/enf_raycast.s: src/enf_raycast.cpp.s
.PHONY : src/enf_raycast.s

# target to generate assembly for a file
src/enf_raycast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_raycast.cpp.s
.PHONY : src/enf_raycast.cpp.s

src/enf_renderer.o: src/enf_renderer.cpp.o
.PHONY : src/enf_renderer.o

# target to build an object file
src/enf_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_renderer.cpp.o
.PHONY : src/enf_renderer.cpp.o

src/enf_renderer.i: src/enf_renderer.cpp.i
.PHONY : src/enf_renderer.i

# target to preprocess a source file
src/enf_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_renderer.cpp.i
.PHONY : src/enf_renderer.cpp.i

src/enf_renderer.s: src/enf_renderer.cpp.s
.PHONY : src/enf_renderer.s

# target to generate assembly for a file
src/enf_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_renderer.cpp.s
.PHONY : src/enf_renderer.cpp.s

src/enf_server.o: src/enf_server.cpp.o
.PHONY : src/enf_server.o

# target to build an object file
src/enf_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_server.cpp.o
.PHONY : src/enf_server.cpp.o

src/enf_server.i: src/enf_server.cpp.i
.PHONY : src/enf_server.i

# target to preprocess a source file
src/enf_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_server.cpp.i
.PHONY : src/enf_server.cpp.i

src/enf_server.s: src/enf_server.cpp.s
.PHONY : src/enf_server.s

# target to generate assembly for a file
src/enf_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_server.cpp.s
.PHONY : src/enf_server.cpp.s

src/enf_sound.o: src/enf_sound.cpp.o
.PHONY : src/enf_sound.o

# target to build an object file
src/enf_sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_sound.cpp.o
.PHONY : src/enf_sound.cpp.o

src/enf_sound.i: src/enf_sound.cpp.i
.PHONY : src/enf_sound.i

# target to preprocess a source file
src/enf_sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_sound.cpp.i
.PHONY : src/enf_sound.cpp.i

src/enf_sound.s: src/enf_sound.cpp.s
.PHONY : src/enf_sound.s

# target to generate assembly for a file
src/enf_sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_sound.cpp.s
.PHONY : src/enf_sound.cpp.s

src/enf_swap_chain.o: src/enf_swap_chain.cpp.o
.PHONY : src/enf_swap_chain.o

# target to build an object file
src/enf_swap_chain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_swap_chain.cpp.o
.PHONY : src/enf_swap_chain.cpp.o

src/enf_swap_chain.i: src/enf_swap_chain.cpp.i
.PHONY : src/enf_swap_chain.i

# target to preprocess a source file
src/enf_swap_chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_swap_chain.cpp.i
.PHONY : src/enf_swap_chain.cpp.i

src/enf_swap_chain.s: src/enf_swap_chain.cpp.s
.PHONY : src/enf_swap_chain.s

# target to generate assembly for a file
src/enf_swap_chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_swap_chain.cpp.s
.PHONY : src/enf_swap_chain.cpp.s

src/enf_texture.o: src/enf_texture.cpp.o
.PHONY : src/enf_texture.o

# target to build an object file
src/enf_texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_texture.cpp.o
.PHONY : src/enf_texture.cpp.o

src/enf_texture.i: src/enf_texture.cpp.i
.PHONY : src/enf_texture.i

# target to preprocess a source file
src/enf_texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_texture.cpp.i
.PHONY : src/enf_texture.cpp.i

src/enf_texture.s: src/enf_texture.cpp.s
.PHONY : src/enf_texture.s

# target to generate assembly for a file
src/enf_texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_texture.cpp.s
.PHONY : src/enf_texture.cpp.s

src/enf_window.o: src/enf_window.cpp.o
.PHONY : src/enf_window.o

# target to build an object file
src/enf_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_window.cpp.o
.PHONY : src/enf_window.cpp.o

src/enf_window.i: src/enf_window.cpp.i
.PHONY : src/enf_window.i

# target to preprocess a source file
src/enf_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_window.cpp.i
.PHONY : src/enf_window.cpp.i

src/enf_window.s: src/enf_window.cpp.s
.PHONY : src/enf_window.s

# target to generate assembly for a file
src/enf_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/enf_window.cpp.s
.PHONY : src/enf_window.cpp.s

src/keyboard.o: src/keyboard.cpp.o
.PHONY : src/keyboard.o

# target to build an object file
src/keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/keyboard.cpp.o
.PHONY : src/keyboard.cpp.o

src/keyboard.i: src/keyboard.cpp.i
.PHONY : src/keyboard.i

# target to preprocess a source file
src/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/keyboard.cpp.i
.PHONY : src/keyboard.cpp.i

src/keyboard.s: src/keyboard.cpp.s
.PHONY : src/keyboard.s

# target to generate assembly for a file
src/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/keyboard.cpp.s
.PHONY : src/keyboard.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/systems/enf_ocean_system.o: src/systems/enf_ocean_system.cpp.o
.PHONY : src/systems/enf_ocean_system.o

# target to build an object file
src/systems/enf_ocean_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_ocean_system.cpp.o
.PHONY : src/systems/enf_ocean_system.cpp.o

src/systems/enf_ocean_system.i: src/systems/enf_ocean_system.cpp.i
.PHONY : src/systems/enf_ocean_system.i

# target to preprocess a source file
src/systems/enf_ocean_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_ocean_system.cpp.i
.PHONY : src/systems/enf_ocean_system.cpp.i

src/systems/enf_ocean_system.s: src/systems/enf_ocean_system.cpp.s
.PHONY : src/systems/enf_ocean_system.s

# target to generate assembly for a file
src/systems/enf_ocean_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_ocean_system.cpp.s
.PHONY : src/systems/enf_ocean_system.cpp.s

src/systems/enf_physics_system.o: src/systems/enf_physics_system.cpp.o
.PHONY : src/systems/enf_physics_system.o

# target to build an object file
src/systems/enf_physics_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_physics_system.cpp.o
.PHONY : src/systems/enf_physics_system.cpp.o

src/systems/enf_physics_system.i: src/systems/enf_physics_system.cpp.i
.PHONY : src/systems/enf_physics_system.i

# target to preprocess a source file
src/systems/enf_physics_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_physics_system.cpp.i
.PHONY : src/systems/enf_physics_system.cpp.i

src/systems/enf_physics_system.s: src/systems/enf_physics_system.cpp.s
.PHONY : src/systems/enf_physics_system.s

# target to generate assembly for a file
src/systems/enf_physics_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_physics_system.cpp.s
.PHONY : src/systems/enf_physics_system.cpp.s

src/systems/enf_point_light_system.o: src/systems/enf_point_light_system.cpp.o
.PHONY : src/systems/enf_point_light_system.o

# target to build an object file
src/systems/enf_point_light_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_point_light_system.cpp.o
.PHONY : src/systems/enf_point_light_system.cpp.o

src/systems/enf_point_light_system.i: src/systems/enf_point_light_system.cpp.i
.PHONY : src/systems/enf_point_light_system.i

# target to preprocess a source file
src/systems/enf_point_light_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_point_light_system.cpp.i
.PHONY : src/systems/enf_point_light_system.cpp.i

src/systems/enf_point_light_system.s: src/systems/enf_point_light_system.cpp.s
.PHONY : src/systems/enf_point_light_system.s

# target to generate assembly for a file
src/systems/enf_point_light_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_point_light_system.cpp.s
.PHONY : src/systems/enf_point_light_system.cpp.s

src/systems/enf_render_system.o: src/systems/enf_render_system.cpp.o
.PHONY : src/systems/enf_render_system.o

# target to build an object file
src/systems/enf_render_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_render_system.cpp.o
.PHONY : src/systems/enf_render_system.cpp.o

src/systems/enf_render_system.i: src/systems/enf_render_system.cpp.i
.PHONY : src/systems/enf_render_system.i

# target to preprocess a source file
src/systems/enf_render_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_render_system.cpp.i
.PHONY : src/systems/enf_render_system.cpp.i

src/systems/enf_render_system.s: src/systems/enf_render_system.cpp.s
.PHONY : src/systems/enf_render_system.s

# target to generate assembly for a file
src/systems/enf_render_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_render_system.cpp.s
.PHONY : src/systems/enf_render_system.cpp.s

src/systems/enf_skybox_system.o: src/systems/enf_skybox_system.cpp.o
.PHONY : src/systems/enf_skybox_system.o

# target to build an object file
src/systems/enf_skybox_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_skybox_system.cpp.o
.PHONY : src/systems/enf_skybox_system.cpp.o

src/systems/enf_skybox_system.i: src/systems/enf_skybox_system.cpp.i
.PHONY : src/systems/enf_skybox_system.i

# target to preprocess a source file
src/systems/enf_skybox_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_skybox_system.cpp.i
.PHONY : src/systems/enf_skybox_system.cpp.i

src/systems/enf_skybox_system.s: src/systems/enf_skybox_system.cpp.s
.PHONY : src/systems/enf_skybox_system.s

# target to generate assembly for a file
src/systems/enf_skybox_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnforcerSyphozia.dir/build.make CMakeFiles/EnforcerSyphozia.dir/src/systems/enf_skybox_system.cpp.s
.PHONY : src/systems/enf_skybox_system.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... custom_clean"
	@echo "... rebuild"
	@echo "... EnforcerSyphozia"
	@echo "... common/assert.o"
	@echo "... common/assert.i"
	@echo "... common/assert.s"
	@echo "... common/config.o"
	@echo "... common/config.i"
	@echo "... common/config.s"
	@echo "... common/discord.o"
	@echo "... common/discord.i"
	@echo "... common/discord.s"
	@echo "... common/logging/filter.o"
	@echo "... common/logging/filter.i"
	@echo "... common/logging/filter.s"
	@echo "... common/logging/text_formatter.o"
	@echo "... common/logging/text_formatter.i"
	@echo "... common/logging/text_formatter.s"
	@echo "... external/imgui/backends/imgui_impl_glfw.o"
	@echo "... external/imgui/backends/imgui_impl_glfw.i"
	@echo "... external/imgui/backends/imgui_impl_glfw.s"
	@echo "... external/imgui/backends/imgui_impl_vulkan.o"
	@echo "... external/imgui/backends/imgui_impl_vulkan.i"
	@echo "... external/imgui/backends/imgui_impl_vulkan.s"
	@echo "... external/imgui/imgui.o"
	@echo "... external/imgui/imgui.i"
	@echo "... external/imgui/imgui.s"
	@echo "... external/imgui/imgui_demo.o"
	@echo "... external/imgui/imgui_demo.i"
	@echo "... external/imgui/imgui_demo.s"
	@echo "... external/imgui/imgui_draw.o"
	@echo "... external/imgui/imgui_draw.i"
	@echo "... external/imgui/imgui_draw.s"
	@echo "... external/imgui/imgui_tables.o"
	@echo "... external/imgui/imgui_tables.i"
	@echo "... external/imgui/imgui_tables.s"
	@echo "... external/imgui/imgui_widgets.o"
	@echo "... external/imgui/imgui_widgets.i"
	@echo "... external/imgui/imgui_widgets.s"
	@echo "... game/player.o"
	@echo "... game/player.i"
	@echo "... game/player.s"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/enf_buffer.o"
	@echo "... src/enf_buffer.i"
	@echo "... src/enf_buffer.s"
	@echo "... src/enf_camera.o"
	@echo "... src/enf_camera.i"
	@echo "... src/enf_camera.s"
	@echo "... src/enf_descriptors.o"
	@echo "... src/enf_descriptors.i"
	@echo "... src/enf_descriptors.s"
	@echo "... src/enf_device.o"
	@echo "... src/enf_device.i"
	@echo "... src/enf_device.s"
	@echo "... src/enf_game_object.o"
	@echo "... src/enf_game_object.i"
	@echo "... src/enf_game_object.s"
	@echo "... src/enf_interface.o"
	@echo "... src/enf_interface.i"
	@echo "... src/enf_interface.s"
	@echo "... src/enf_model.o"
	@echo "... src/enf_model.i"
	@echo "... src/enf_model.s"
	@echo "... src/enf_pipeline.o"
	@echo "... src/enf_pipeline.i"
	@echo "... src/enf_pipeline.s"
	@echo "... src/enf_raycast.o"
	@echo "... src/enf_raycast.i"
	@echo "... src/enf_raycast.s"
	@echo "... src/enf_renderer.o"
	@echo "... src/enf_renderer.i"
	@echo "... src/enf_renderer.s"
	@echo "... src/enf_server.o"
	@echo "... src/enf_server.i"
	@echo "... src/enf_server.s"
	@echo "... src/enf_sound.o"
	@echo "... src/enf_sound.i"
	@echo "... src/enf_sound.s"
	@echo "... src/enf_swap_chain.o"
	@echo "... src/enf_swap_chain.i"
	@echo "... src/enf_swap_chain.s"
	@echo "... src/enf_texture.o"
	@echo "... src/enf_texture.i"
	@echo "... src/enf_texture.s"
	@echo "... src/enf_window.o"
	@echo "... src/enf_window.i"
	@echo "... src/enf_window.s"
	@echo "... src/keyboard.o"
	@echo "... src/keyboard.i"
	@echo "... src/keyboard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/systems/enf_ocean_system.o"
	@echo "... src/systems/enf_ocean_system.i"
	@echo "... src/systems/enf_ocean_system.s"
	@echo "... src/systems/enf_physics_system.o"
	@echo "... src/systems/enf_physics_system.i"
	@echo "... src/systems/enf_physics_system.s"
	@echo "... src/systems/enf_point_light_system.o"
	@echo "... src/systems/enf_point_light_system.i"
	@echo "... src/systems/enf_point_light_system.s"
	@echo "... src/systems/enf_render_system.o"
	@echo "... src/systems/enf_render_system.i"
	@echo "... src/systems/enf_render_system.s"
	@echo "... src/systems/enf_skybox_system.o"
	@echo "... src/systems/enf_skybox_system.i"
	@echo "... src/systems/enf_skybox_system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

